import { useState } from 'react';

type AuthPageProps = { mode: 'login' | 'create'; onNavigate: (path: '/login' | '/create-account' | '/expenses') => void; onToast: (message: string) => void };

function AuthPages({ mode, onNavigate, onToast }: AuthPageProps) {
  const isLogin = mode === 'login'; const [showPassword, setShowPassword] = useState(false);
  return <main className="auth-shell"><section className="auth-brand"><div className="auth-logo">A<span>✦</span>T</div><p className="eyebrow">THE ARCANE SUITE</p><h1>Make room<br />for magic.</h1><p>One quiet place to keep track of the gold, plans, and small rituals that make a life.</p><span className="auth-orbit">✧</span></section><section className="auth-form-wrap"><div className="auth-form"><p className="eyebrow">WELCOME BACK</p><h2>{isLogin ? 'Open your tome' : 'Begin your tome'}</h2><p className="auth-subtitle">{isLogin ? 'Enter your details to continue.' : 'A few details, then you are ready to begin.'}</p><form onSubmit={(event) => { event.preventDefault(); onNavigate('/expenses'); onToast(isLogin ? 'Welcome back, Mira.' : 'Your tome has been created.'); }}><div className="auth-name-fields">{!isLogin && <label>FIRST NAME<input required placeholder="Mira" /></label>}{!isLogin && <label>LAST NAME<input required placeholder="Vale" /></label>}</div><label>EMAIL<input required type="email" placeholder="you@example.com" /></label><label>PASSWORD<div className="password-field"><input required type={showPassword ? 'text' : 'password'} placeholder="••••••••" /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'Hide' : 'Show'}</button></div></label>{isLogin ? <div className="remember-row"><label><input type="checkbox" defaultChecked /> Remember me</label><button type="button" className="text-button" onClick={() => onToast('Password reset instructions are on the way.')}>Forgot password?</button></div> : <label className="terms"><input required type="checkbox" /> I agree to the terms of the Arcane Tome.</label>}<button className="auth-submit" type="submit">{isLogin ? 'OPEN TOME' : 'CREATE ACCOUNT'} <span>↗</span></button></form><div className="auth-switch">{isLogin ? 'New to the suite?' : 'Already have a tome?'} <button type="button" onClick={() => onNavigate(isLogin ? '/create-account' : '/login')}>{isLogin ? 'Create an account' : 'Sign in'}</button></div></div></section></main>;
}

export default AuthPages;
