import { useState } from 'react';

type SettingsPageProps = { mode?: 'settings' | 'photo' | 'password'; onNavigate: (path: '/settings' | '/settings/photo' | '/settings/password') => void; onToast: (message: string) => void };

function SettingsPage({ mode = 'settings', onNavigate, onToast }: SettingsPageProps) {
  if (mode === 'photo') return <PhotoPage onBack={() => onNavigate('/settings')} onSaved={onToast} />;
  if (mode === 'password') return <PasswordPage onBack={() => onNavigate('/settings')} onSaved={onToast} />;
  return <SettingsOverview onNavigate={onNavigate} onSaved={onToast} />;
}

function SettingsOverview({ onNavigate, onSaved }: { onNavigate: SettingsPageProps['onNavigate']; onSaved: (message: string) => void }) {
  const [weekly, setWeekly] = useState(true); const [budget, setBudget] = useState(true); const [currency, setCurrency] = useState('Indonesian Rupiah (Rp)');
  return <main className="workspace"><section className="settings-content" aria-labelledby="settings-title"><header className="content-header"><div><p className="eyebrow">YOUR TOME <span>•</span> PREFERENCES</p><h2 id="settings-title">Settings</h2><p className="lede">Shape your ledger to fit the way you live.</p></div></header><div className="settings-layout"><form className="settings-form" onSubmit={(event) => { event.preventDefault(); onSaved('Your settings have been saved.'); }}><section className="settings-section"><div className="settings-section-heading"><h3>Profile</h3><button className="text-button" type="button" onClick={() => onNavigate('/settings/photo')}>Change photo</button></div><div className="settings-profile"><div className="settings-avatar">MV</div><div><strong>Mira Vale</strong><span>mira@arcane.tome</span></div></div><div className="form-grid"><label>FIRST NAME<input defaultValue="Mira" /></label><label>LAST NAME<input defaultValue="Vale" /></label></div><label>EMAIL ADDRESS<input type="email" defaultValue="mira@arcane.tome" /></label></section><section className="settings-section"><h3>Preferences</h3><label className="select-label">CURRENCY<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option>Indonesian Rupiah (Rp)</option><option>US Dollar ($)</option><option>Euro (€)</option></select></label><div className="toggle-setting"><div><strong>Weekly summary</strong><span>Receive a quiet report every Monday.</span></div><button type="button" className={`toggle ${weekly ? 'on' : ''}`} aria-pressed={weekly} onClick={() => setWeekly(!weekly)}><span /></button></div><div className="toggle-setting"><div><strong>Budget reminders</strong><span>Let the archivist warn you before a limit.</span></div><button type="button" className={`toggle ${budget ? 'on' : ''}`} aria-pressed={budget} onClick={() => setBudget(!budget)}><span /></button></div></section><section className="settings-section security-row"><div><h3>Security</h3><p>Keep your account wards up to date.</p></div><button className="text-button" type="button" onClick={() => onNavigate('/settings/password')}>Update password ↗</button></section><div className="settings-actions"><button className="save" type="submit">SAVE CHANGES</button></div></form><aside className="settings-aside"><p className="summary-kicker">ARCANE TOME</p><h3>Your preferences are yours.</h3><p>We keep your financial notes private and only use them to make your ledger more useful.</p><span className="privacy-sigil">✦</span></aside></div></section></main>;
}

function PhotoPage({ onBack, onSaved }: { onBack: () => void; onSaved: (message: string) => void }) {
  const [fileName, setFileName] = useState('');
  return <main className="workspace"><section className="form-page settings-child" aria-labelledby="photo-title"><button className="back-link" type="button" onClick={onBack}>← Back to settings</button><div className="form-heading"><p className="eyebrow">PROFILE <span>•</span> PORTRAIT</p><h2 id="photo-title">Change your photo</h2><p>Choose an image for the face of your tome.</p></div><div className="photo-upload"><div className="large-avatar">{fileName ? 'MV' : '✦'}</div><label className="upload-zone">{fileName || 'Drop an image here, or browse'}<input type="file" accept="image/png,image/jpeg" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? '')} /></label><small>JPG or PNG, up to 2 MB</small></div><div className="form-actions"><button className="cancel" type="button" onClick={onBack}>CANCEL</button><button className="save" type="button" disabled={!fileName} onClick={() => { onBack(); onSaved('Profile photo updated.'); }}>SAVE PHOTO</button></div></section></main>;
}

function PasswordPage({ onBack, onSaved }: { onBack: () => void; onSaved: (message: string) => void }) {
  const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  const valid = newPassword.length >= 8 && newPassword === confirmation;
  return <main className="workspace"><section className="form-page settings-child" aria-labelledby="password-title"><button className="back-link" type="button" onClick={onBack}>← Back to settings</button><div className="form-heading"><p className="eyebrow">SECURITY <span>•</span> ACCOUNT WARD</p><h2 id="password-title">Update password</h2><p>Make a new key for your private ledger.</p></div><form className="expense-form" onSubmit={(event) => { event.preventDefault(); onBack(); onSaved('Password updated successfully.'); }}><label>CURRENT PASSWORD<input required type="password" /></label><label>NEW PASSWORD<input required type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><label>CONFIRM NEW PASSWORD<input required type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><ul className="password-rules"><li className={newPassword.length >= 8 ? 'met' : ''}>At least 8 characters</li><li className={/[A-Z]/.test(newPassword) ? 'met' : ''}>One capital letter</li><li className={newPassword === confirmation && confirmation.length > 0 ? 'met' : ''}>Passwords match</li></ul><div className="form-actions"><button className="cancel" type="button" onClick={onBack}>CANCEL</button><button className="save" type="submit" disabled={!valid}>UPDATE PASSWORD</button></div></form></section></main>;
}

export default SettingsPage;
