import { useState } from 'react';
import { spendingCategories, spendingBars } from '../services/dashboardData';

type SummaryPageProps = { onToast: (message: string) => void };

function SummaryPage({ onToast }: SummaryPageProps) {
  const [period, setPeriod] = useState('This month');
  return <main className="workspace"><section className="content summary-page" aria-labelledby="summary-page-title"><header className="content-header"><div><p className="eyebrow">FINANCIAL REPORT <span>•</span> 2026</p><h2 id="summary-page-title">Summary</h2><p className="lede">A wider view of the patterns in your ledger.</p></div><div className="summary-actions"><select value={period} onChange={(event) => setPeriod(event.target.value)} aria-label="Summary period"><option>This month</option><option>Last month</option><option>This year</option></select><button className="add-button" type="button" onClick={() => onToast('Summary export is ready to download.')}>EXPORT <span>↗</span></button></div></header><div className="metric-grid"><article><span>INCOME</span><strong>Rp 18.500.000</strong><small className="positive">+ 12.4%</small></article><article><span>EXPENSES</span><strong>Rp 5.859.500</strong><small className="negative">+ 4.8%</small></article><article><span>SET ASIDE</span><strong>Rp 3.240.000</strong><small className="positive">+ 18.1%</small></article></div><div className="report-grid"><section className="report-card trend-card"><div className="section-title"><h3>Spending trend</h3><span>Mar 01 - 25</span></div><div className="trend-chart">{spendingBars.map((height, index) => <span key={index} style={{ height: `${Math.max(14, height - 10)}%` }} />)}</div><div className="chart-labels"><span>01 Mar</span><span>12 Mar</span><span>25 Mar</span></div></section><section className="report-card"><div className="section-title"><h3>Top categories</h3></div>{spendingCategories.slice(0, 4).map((category) => <div className="rank-row" key={category.label}><span>{category.label}</span><b>{category.amount}</b><div className="progress"><span className={category.tone} style={{ width: `${category.percentage}%` }} /></div></div>)}</section></div></section><aside className="summary report-aside"><p className="summary-kicker">MONTHLY INSIGHT</p><h3>Your spending has a rhythm.</h3><p>Most of your activity arrives around the middle of the cycle. A little planning there could protect your rainy day fund.</p><div className="donut small"><span>32%<small>needs</small></span></div><button className="save insight-button" type="button" onClick={() => onToast('Insight saved to your journal.')}>SAVE INSIGHT</button></aside></main>;
}

export default SummaryPage;
